### ISSUE TITLE
Неправильный перевод на английский

### ISSUE THREAD

**Issue by nokomotc** [SurgeBrawlTeam/SurgeBrawl-Translations#1]
"smallgift": "A small gift before a big one" 
если что - прилагательные не привязанные к чему-либо использовать нельзя, потому вставлено слово one. Смысл поменяться не должен был

**Comment by nokomotc** [comment]
Ах да, использование in front of тут некорректно, потому что это просто русское регулярное выражение

**Comment by nokomotc** [comment]
блен, надо же label поставить...

**Comment by nokomotc** [comment]
уже поздно

**Comment by nokomotc** [comment]
я тупой

**Comment by tailsjs** [comment]
Упс, моя ошибка.
До этого была строка в русском переводе "Маленький подарок до большого" (ещё до репозитория)
Я решил исправить эту строку + передумать идею как можно её использовать, но забыл её исправить в английском контейнере с текстом.
Поправлю.
Предлагаю "A small gift before something great" (Небольшой подарок до кое-чего хорошего)
Всё-же я мог бы написать "A small gift, after which there will be something good" (Небольшой подарок, после которого будет кое-что хорошее), но опасаюсь того, что из-за длины текст строки будет нечитаемым.
Смысл вроде изменится не должен (Как в русском языке идёт упоминание какого-то подарка, после небольшого, так и в английском)
