### ISSUE TITLE
Новые строки, новая иссуя:

### ISSUE THREAD

**Issue by nokomotc** [SurgeBrawlTeam/SurgeBrawl-Translations#3]
"error": "An error has been occured! Please try rejoin!"
An error occured! Please try blah*
* - два варианта, либо to rejoin, либо rejoining

**Comment by tailsjs** [comment]
предлагаю заменить эту строку на "An error has been occured! Please reconnect!"

**Comment by nokomotc** [comment]
@tailsjs думаю вполне неплохой варик
UPD: как слово
